### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by karikarshivani** [CMSgov/cms-ars-5.0-microsoft-windows-server-2019-stig-overlay#4]
- [x] Non-ARS check: Use the NA Caveats worksheet (column I) to check if any Windows 2019 controls are not in ARS.
- [x] Remove sys_cat verbiage: In the for loop, change the caveat to `"Not applicable for this CMS ARS 5.0 overlay, since the requirement is not included in CMS ARS 5.0"`
- [x] Add comments similar to RHEL 8 for NIST tag updates: for example, `tag nist: ["PL-9"] # PL-9 incorporates withdrawn control AU-3 (2)`

Use [Windows 2019 workbook](https://github.com/CMSgov/cms-ars-5.0-microsoft-windows-server-2019-stig-overlay/files/9902356/Win2019NISTControls.xlsx) to access the controls

**Comment by ssayed118** [comment]
- Compared column I of the worksheet with the WIN2019 workbooks and did not find any duplicates between the 2 
- Updated caveat statement
- Possible tag updates: AU-8(1), CA-3(5), IA-2(3), IA-2(4), IA-2(9), IA-2(11),  IA-2(4)e

**Comment by ssayed118** [comment]
Issues were fixed with the 3c4f8f8af9798f6797559f247d843608ecda7431 commit from the baseline. 
V-93441 still needs to be checked

**Comment by ssayed118** [comment]
Issues were fixed with the 3c4f8f8af9798f6797559f247d843608ecda7431 commit from the baseline.
